### ISSUE TITLE
Some Questions about Genarate Semiuniform Mesh

### ISSUE THREAD

**Issue by heijie750622** [cemcen/vemlab#1]
Hello, I am experiencing difficulties with creating custom meshes in my project. I have searched through the documentation, but I have not been able to generate the semi-uniform elements that are present in the 'unit_disk_poisson2d_993poly_elems_semiuniform_ssalinas.txt' file. It seems that the mesh generation functions provided in the source code of VEMLAB are not generating the desired mesh. Could you please assist me in troubleshooting this issue and provide guidance on how to generate these semi-uniform elements? Thank you for your time and assistance.

**Comment by aaortizb** [comment]
Hello, I hadn't seen this message before. The mesh you are trying to reproduce is not implemented in vemlab. That mesh file was created with:

https://github.com/ssalinasfe/Polylla-Mesh-DCEL

and then the mesh exported to vemlab format.
